### ISSUE TITLE
Profile Page - credential entry

### ISSUE THREAD

**Issue by SamLarivs** [oslabs-beta/TrailGuide#29]
### Problem

As a user, I want to be able to input my AWS credentials to validate my AWS account. Without an entry form, I have no way of accessing my current logs for visualization tools in the app.

### Solution

We can solve the problem by creating forms for AWS credential input on the user profile page. This will be hashed and placed in our database. This will allow the user to safely connect their AWS account in a way that is more efficient and secure. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd love to make a PR to implement this feature!

**Comment by aidanprior** [comment]
Connect to the backend
