### ISSUE TITLE
User Access Control

### ISSUE THREAD

**Issue by homosapientdream** [oslabs-beta/TrailGuide#59]
### Problem

1. Login Functionality: Ensure users must log in to access restricted parts of the application.
2. Logout Functionality: Redirect users to the login page after logging out.
3. Dashboard Access Control: Users can only see the dashboard if they are logged in.
4. Signup Redirect: Unauthenticated users should be redirected to the signup page if trying to access restricted content.

### Solution

1. Implement user authentication using a method such as JSON Web Tokens (JWT), session cookies, or OAuth.
2. Protect restricted routes (e.g., the dashboard) by checking if a user is authenticated before granting access.
If a user is not authenticated, redirect them to the login page.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd love to make a PR to implement this feature!

**Comment by SamLarivs** [comment]
Lets get caught up with Aidan on this feature. I think his most recent pull request handles some of this issue.
